name: 'Setup Vulkan SDK multiplatform'
description: 'Setup Vulkan SDK using GitHub Actions'
inputs:
  version:
    description: 'Vulkan SDK version to install'
    default: '1.3.296.0'
    required: true
  components:
    description: 'List of Vulkan SDK components to install (e.g., Vulkan-Headers, Vulkan-Loader, Glslang)'
    default: 'Vulkan-Headers,Vulkan-Loader'
    required: true
  cache:
    description: 'Enable caching for Vulkan SDK'
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    # detect os
    - name: Detect OS
      shell: bash
      run: echo "Running on $RUNNER_OS"

    # windows
    - name: Download Vulkan SDK (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl -LO "https://sdk.lunarg.com/sdk/download/${{ inputs.version }}/windows/VulkanSDK-${{ inputs.version }}-Installer.exe"
        start VulkanSDK-${{ inputs.version }}-Installer.exe /S /COMPONENTS="${{ inputs.components }}"
        echo "VULKAN_SDK=C:\\VulkanSDK\\${{ inputs.version }}" >> $GITHUB_ENV
        echo "Path=$VULKAN_SDK\\Bin;$Path" >> $GITHUB_ENV

    # linux
    - name: Install Vulkan SDK (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -LO https://sdk.lunarg.com/sdk/download/${{ inputs.version }}/linux/vulkansdk-linux-x86_64-${{ inputs.version }}.tar.xz
        sudo mkdir -p /opt/VulkanSDK
        sudo tar -xvf vulkansdk-linux-x86_64-${{ inputs.version }}.tar.xz -C /opt/VulkanSDK
        echo "VULKAN_SDK=/opt/VulkanSDK/${{ inputs.version }}/x86_64" >> $GITHUB_ENV
        echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV
        if [ -n "${{ inputs.components }}" ]; then
          sudo bash /opt/VulkanSDK/${{ inputs.version }}/setup-env.sh --install-components "${{ inputs.components }}"
        fi

    # macos
    - name: Install Vulkan SDK (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -LO https://sdk.lunarg.com/sdk/download/${{ inputs.version }}/mac/vulkansdk-macos-${{ inputs.version }}.zip
        unzip vulkansdk-macos-${{ inputs.version }}.zip -d /Applications/VulkanSDK
        echo "VULKAN_SDK=/Applications/VulkanSDK/${{ inputs.version }}/macOS" >> $GITHUB_ENV
        echo "PATH=$VULKAN_SDK/bin:$PATH" >> $GITHUB_ENV

    # cache
    - name: Cache Vulkan SDK
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ${{ runner.os == 'Windows' && 'C:\\VulkanSDK\\${{ inputs.version }}' || '' }}
          ${{ runner.os == 'Linux' && '/opt/VulkanSDK/${{ inputs.version }}/x86_64' || '' }}
          ${{ runner.os == 'macOS' && '/Applications/VulkanSDK/${{ inputs.version }}/macOS' || '' }}
        key: vulkan-sdk-${{ inputs.version }}-${{ runner.os }}