name: 'Test Vulkan SDK Installation'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-vulkan-sdk:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['1.3.296.0']
        components: ['Vulkan-Headers,Vulkan-Loader']

    steps:
    - name: Set up Vulkan SDK
      uses: SpargatTeam/setup-vulkan-sdk@main
      with:
        version: ${{ matrix.version }}
        components: ${{ matrix.components }}
        cache: 'true'